web-server:
  image: node:12.5.0
  ports:
    - "80:80"
  volumes:
    - ./node:/node
  working_dir: /node/
  command: npm start
  links:
    - mongodb
  
mongodb:
  container_name: mongodb
  image: mongo
  ports:
    - "27017:27017"
  volumes:
    - ./mongodb/:/data/db
